spring.application.name=bankaccount_management_system
server.port=${API_PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/bank_db}
spring.datasource.username=${DB_USER:bank_user}
spring.datasource.password=${DB_PASSWORD:bank_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
